### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by brendon** [Envek/durable-websockets#1]
Hi @Envek, this looks interesting. I see it never went past an initial commit. These days, what would you recommend for durable websockets for Rails?

**Comment by Envek** [comment]
Hi! This was extracted from one of production applications and was used as a example/playground/reference for my talk at SaintP Ruby Conference 2017 (slides in Russian are [here](https://speakerdeck.com/envek/saintprubyconf-2017-durable-websockets)).

Since then, I had not any need in such a setup, so I didn't use it anymore. And have no plans to continue develop it.

Yes, I can recommend it if you 100% need to guarantee that every single message will be delivered. However, in reality it is not so strict requirement (so some simpler workaraunds may be good enough).

And RabbitMQ is quite difficult to properly set up, monitor, and scale (it is not suitable in case if you need tens of thousands client). And it isn't popular now. So at least take a look on other message brokers.

**Comment by brendon** [comment]
Thanks @Envek, I very much appreciate the feedback :) My current strategy on a new app I'm creating is upon reconnect to just refresh the Vuex stores from the server. I'll just have to come up with a strategy for what to do if a user is in the middle editing something. Thanks again! :)

**Comment by Envek** [comment]
If you can just refetch everything, it is the most simple approach.

This approach with message broker and acknowledging every message when it was not viable to redownload all the state: when internet connection is very-very slow and unreliable (e.g. 2G EDGE/GPRS cellular network with poor coverage)

One more thing you can also consider is [Logux](https://logux.io/): special framework for building offline-first and collaborative applications. It also has [Vuex support](https://logux.io/guide/starting/replace-vuex/).

**Comment by brendon** [comment]
Logux looks great! It even has Rails support which is a bonus :) I'll definitely look further into that. Thank you again for all your help :D
